server:
  port: 8761
eureka:
  client: 
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
spring:
  redis:
    host: 192.168.125.128  # 此处为不缓存页面