server:
   port: 8003
spring:
    application:
      name: log-queue
    kafka:
      bootstrap-servers: 127.0.0.1:9092
      consumer:
         group-id: group1
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/