server:
   port: 8003
spring:
    application:
      name: log-queue
    kafka:
      bootstrap-servers: 140.143.227.194:9092
      consumer:
         group-id: group1
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://140.143.227.194:8761/eureka/